version: '3'
services:
  devops:
    image: ramu478/azure
    ports:
      - "90:80"
    deploy:
      replicas: 3

  aws:
    image: ramu478/aws
    ports:
      - "91:80"
    deploy:
      replicas: 3

  datascience:
    image: ramu478/ds
    ports:
      - "92:80"
    deploy:
      replicas: 3

  azure:
    image: ramu478/devops
    ports:
      - "93:80"
    deploy:
      replicas: 3
